Fordeling av stortingsmandatene
===============================

Dette er en oversikt over fordelingene av stortingsmandatene. De to første tabellene bruker de faktiske tallene for folketall og areal, mens resten bruker Statistisk sentralbyrås framskrevne befolkningstall.

```{r data,echo=FALSE}
Mandatfordelingsdata <-
  read.csv("Mandatfordelingsdata.csv", sep=";")
Mandatfordelingsdata <- transform(Mandatfordelingsdata,
                                  År=as.factor(År))
source('saintelague.R')
Mandatfordelingsdata$Mandater <-
  c(
    saintelague(169,
                Mandatfordelingsdata[
                  Mandatfordelingsdata$År==2004, ]$Areal * 1.8
                +
                  Mandatfordelingsdata[
                    Mandatfordelingsdata$År==2004, ]$Folketall),
    saintelague(169,
                Mandatfordelingsdata[
                  Mandatfordelingsdata$År==2012, ]$Areal * 1.8
                +
                  Mandatfordelingsdata[
                    Mandatfordelingsdata$År==2012, ]$Folketall),
    saintelague(169,
                Mandatfordelingsdata[
                  Mandatfordelingsdata$År==2020, ]$Areal * 1.8
                +
                  Mandatfordelingsdata[
                    Mandatfordelingsdata$År==2020, ]$Folketall),
    saintelague(169,
                Mandatfordelingsdata[
                  Mandatfordelingsdata$År==2028, ]$Areal * 1.8
                +
                  Mandatfordelingsdata[
                    Mandatfordelingsdata$År==2028, ]$Folketall),
    saintelague(169,
                Mandatfordelingsdata[
                  Mandatfordelingsdata$År==2036, ]$Areal * 1.8
                +
                  Mandatfordelingsdata[
                    Mandatfordelingsdata$År==2036, ]$Folketall)
    )
```

```{r print, results='asis',echo=FALSE}
library("xtable")
mandattabell <- function(år) {
  m <- subset(Mandatfordelingsdata, År == år)
  if (år == 2004) {
    m$Endring <- m$Mandater - c(8, 15, 16, 8, 7, 7, 8, 6, 4, 5, 11,
                                17, 5, 10, 10, 6, 12, 6, 4)
    } else {
      m$Endring <- m$Mandater - subset(Mandatfordelingsdata,
                                       År == år - 8)$Mandater
      }
  m$År  <- NULL
  m[m==0] <- NA
  mx <- print(xtable(m,caption = paste("Mandatfordeling ",
                                      år + 1,
                                      "--",
                                      år + 9,
                                      sep = ""),
                     label = paste("tab:m",
                                   år,
                                   sep = ""),
                     digits = 0),
              include.rownames = FALSE,
              caption.placement = "top",
              type="html")
  }
```

Første tabell:

```{r 2004, results='asis',echo=FALSE}
mandattabell(2004)
```

Andre tabell:

```{r 2012, results='asis',echo=FALSE}
mandattabell(2012)
```

Tredje tabell:

```{r 2020, results='asis',echo=FALSE}
mandattabell(2020)
```

Fjerde tabell:

```{r 2028, results='asis',echo=FALSE}
mandattabell(2028)
```

Femte tabell:

```{r 2036, results='asis',echo=FALSE}
mandattabell(2036)
```
